"""Add attendance table

Revision ID: 303f6bfb1902
Revises: 5a34567f5e2c
Create Date: 2021-11-30 16:35:08.335829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303f6bfb1902'
down_revision = '5a34567f5e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
